// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: binance/spot/tradings/scalping/scalping.proto

package scalping

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ScalpingClient is the client API for Scalping service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScalpingClient interface {
	Pagenate(ctx context.Context, in *PagenateRequest, opts ...grpc.CallOption) (*PagenateReply, error)
}

type scalpingClient struct {
	cc grpc.ClientConnInterface
}

func NewScalpingClient(cc grpc.ClientConnInterface) ScalpingClient {
	return &scalpingClient{cc}
}

func (c *scalpingClient) Pagenate(ctx context.Context, in *PagenateRequest, opts ...grpc.CallOption) (*PagenateReply, error) {
	out := new(PagenateReply)
	err := c.cc.Invoke(ctx, "/taoniu.local.cryptos.grpc.binance.spot.tradings.scalping.Scalping/Pagenate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScalpingServer is the server API for Scalping service.
// All implementations must embed UnimplementedScalpingServer
// for forward compatibility
type ScalpingServer interface {
	Pagenate(context.Context, *PagenateRequest) (*PagenateReply, error)
	mustEmbedUnimplementedScalpingServer()
}

// UnimplementedScalpingServer must be embedded to have forward compatible implementations.
type UnimplementedScalpingServer struct {
}

func (UnimplementedScalpingServer) Pagenate(context.Context, *PagenateRequest) (*PagenateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pagenate not implemented")
}
func (UnimplementedScalpingServer) mustEmbedUnimplementedScalpingServer() {}

// UnsafeScalpingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScalpingServer will
// result in compilation errors.
type UnsafeScalpingServer interface {
	mustEmbedUnimplementedScalpingServer()
}

func RegisterScalpingServer(s grpc.ServiceRegistrar, srv ScalpingServer) {
	s.RegisterService(&Scalping_ServiceDesc, srv)
}

func _Scalping_Pagenate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PagenateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScalpingServer).Pagenate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taoniu.local.cryptos.grpc.binance.spot.tradings.scalping.Scalping/Pagenate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScalpingServer).Pagenate(ctx, req.(*PagenateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Scalping_ServiceDesc is the grpc.ServiceDesc for Scalping service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Scalping_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "taoniu.local.cryptos.grpc.binance.spot.tradings.scalping.Scalping",
	HandlerType: (*ScalpingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pagenate",
			Handler:    _Scalping_Pagenate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "binance/spot/tradings/scalping/scalping.proto",
}
