package queue

const (
  BINANCE_SPOT_TICKERS                          = "cryptos.jobs.binance.spot.tickers"
  BINANCE_SPOT_TICKERS_DELAY                    = "cryptos.jobs.binance.spot.tickers.delay"
  BINANCE_SPOT_KLINES                           = "cryptos.jobs.binance.spot.klines"
  BINANCE_SPOT_KLINES_DELAY                     = "cryptos.jobs.binance.spot.klines.delay"
  BINANCE_SPOT_DEPTH                            = "cryptos.jobs.binance.spot.depth"
  BINANCE_SPOT_DEPTH_DELAY                      = "cryptos.jobs.binance.spot.depth.delay"
  BINANCE_SPOT_ACCOUNT                          = "cryptos.jobs.binance.spot.account"
  BINANCE_SPOT_ORDERS                           = "cryptos.jobs.binance.spot.orders"
  BINANCE_SPOT_INDICATORS                       = "cryptos.jobs.binance.spot.indicators"
  BINANCE_SPOT_STRATEGIES                       = "cryptos.jobs.binance.spot.strategies"
  BINANCE_SPOT_PLANS                            = "cryptos.jobs.binance.spot.plans"
  BINANCE_SPOT_TRADINGS_LAUNCHPAD               = "cryptos.jobs.binance.spot.tradings.launchpad"
  BINANCE_SPOT_TRADINGS_SCALPING                = "cryptos.jobs.binance.spot.tradings.scalping"
  BINANCE_SPOT_TRADINGS_TRIGGERS                = "cryptos.jobs.binance.spot.tradings.triggers"
  BINANCE_SPOT_MARGIN_CROSS_TRADINGS_TRIGGERS   = "cryptos.jobs.binance.spot.margin.cross.tradings.triggers"
  BINANCE_SPOT_MARGIN_ISOLATED_TRADINGS_FISHERS = "cryptos.jobs.binance.spot.margin.isolated.tradings.fishers"
  BINANCE_FUTURES_TICKERS                       = "cryptos.jobs.binance.futures.tickers"
  BINANCE_FUTURES_TICKERS_DELAY                 = "cryptos.jobs.binance.futures.tickers.delay"
  BINANCE_FUTURES_KLINES                        = "cryptos.jobs.binance.futures.klines"
  BINANCE_FUTURES_KLINES_DELAY                  = "cryptos.jobs.binance.futures.klines.delay"
  BINANCE_FUTURES_DEPTH                         = "cryptos.jobs.binance.futures.depth"
  BINANCE_FUTURES_DEPTH_DELAY                   = "cryptos.jobs.binance.futures.depth.delay"
  BINANCE_FUTURES_ACCOUNT                       = "cryptos.jobs.binance.futures.account"
  BINANCE_FUTURES_ORDERS                        = "cryptos.jobs.binance.futures.orders"
  BINANCE_FUTURES_INDICATORS                    = "cryptos.jobs.binance.futures.indicators"
  BINANCE_FUTURES_STRATEGIES                    = "cryptos.jobs.binance.futures.strategies"
  BINANCE_FUTURES_PLANS                         = "cryptos.jobs.binance.futures.plans"
  BINANCE_FUTURES_TRADINGS_TRIGGERS             = "cryptos.jobs.binance.futures.tradings.triggers"
  BINANCE_FUTURES_TRADINGS_SCALPING             = "cryptos.jobs.binance.futures.tradings.scalping"
  DYDX_ORDERBOOK                                = "cryptos.jobs.dydx.orderbook"
  DYDX_ORDERBOOK_DELAY                          = "cryptos.jobs.dydx.orderbook.delay"
  DYDX_KLINES                                   = "cryptos.jobs.dydx.klines"
  DYDX_KLINES_DELAY                             = "cryptos.jobs.dydx.klines.delay"
  DYDX_ACCOUNT                                  = "cryptos.jobs.dydx.account"
  DYDX_ORDERS                                   = "cryptos.jobs.dydx.orders"
  DYDX_INDICATORS                               = "cryptos.jobs.dydx.indicators"
  DYDX_STRATEGIES                               = "cryptos.jobs.dydx.strategies"
  DYDX_PLANS                                    = "cryptos.jobs.dydx.plans"
  DYDX_TRADINGS_TRIGGERS                        = "cryptos.jobs.dydx.tradings.triggers"
  DYDX_TRADINGS_SCALPING                        = "cryptos.jobs.dydx.tradings.scalping"
  TRADINGVIEW_ANALYSIS                          = "tradingview.jobs.analysis"
  TRADINGVIEW_ANALYSIS_DELAY                    = "tradingview.jobs.analysis.delay"
)
