// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: binance/futures/plans/plans.proto

package plans

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PlansClient is the client API for Plans service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlansClient interface {
	Paginate(ctx context.Context, in *PaginateRequest, opts ...grpc.CallOption) (*PaginateReply, error)
}

type plansClient struct {
	cc grpc.ClientConnInterface
}

func NewPlansClient(cc grpc.ClientConnInterface) PlansClient {
	return &plansClient{cc}
}

func (c *plansClient) Paginate(ctx context.Context, in *PaginateRequest, opts ...grpc.CallOption) (*PaginateReply, error) {
	out := new(PaginateReply)
	err := c.cc.Invoke(ctx, "/taoniu.local.cryptos.grpc.binance.futures.plans.Plans/Paginate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlansServer is the server API for Plans service.
// All implementations must embed UnimplementedPlansServer
// for forward compatibility
type PlansServer interface {
	Paginate(context.Context, *PaginateRequest) (*PaginateReply, error)
	mustEmbedUnimplementedPlansServer()
}

// UnimplementedPlansServer must be embedded to have forward compatible implementations.
type UnimplementedPlansServer struct {
}

func (UnimplementedPlansServer) Paginate(context.Context, *PaginateRequest) (*PaginateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Paginate not implemented")
}
func (UnimplementedPlansServer) mustEmbedUnimplementedPlansServer() {}

// UnsafePlansServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlansServer will
// result in compilation errors.
type UnsafePlansServer interface {
	mustEmbedUnimplementedPlansServer()
}

func RegisterPlansServer(s grpc.ServiceRegistrar, srv PlansServer) {
	s.RegisterService(&Plans_ServiceDesc, srv)
}

func _Plans_Paginate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaginateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlansServer).Paginate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taoniu.local.cryptos.grpc.binance.futures.plans.Plans/Paginate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlansServer).Paginate(ctx, req.(*PaginateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Plans_ServiceDesc is the grpc.ServiceDesc for Plans service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Plans_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "taoniu.local.cryptos.grpc.binance.futures.plans.Plans",
	HandlerType: (*PlansServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Paginate",
			Handler:    _Plans_Paginate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "binance/futures/plans/plans.proto",
}
