// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: account/mqtt/publishers/publishers.proto

package publishers

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PublishersClient is the client API for Publishers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PublishersClient interface {
	Token(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenReply, error)
}

type publishersClient struct {
	cc grpc.ClientConnInterface
}

func NewPublishersClient(cc grpc.ClientConnInterface) PublishersClient {
	return &publishersClient{cc}
}

func (c *publishersClient) Token(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenReply, error) {
	out := new(TokenReply)
	err := c.cc.Invoke(ctx, "/taoniu.local.account.grpc.mqtt.publishers.Publishers/Token", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublishersServer is the server API for Publishers service.
// All implementations must embed UnimplementedPublishersServer
// for forward compatibility
type PublishersServer interface {
	Token(context.Context, *TokenRequest) (*TokenReply, error)
	mustEmbedUnimplementedPublishersServer()
}

// UnimplementedPublishersServer must be embedded to have forward compatible implementations.
type UnimplementedPublishersServer struct {
}

func (UnimplementedPublishersServer) Token(context.Context, *TokenRequest) (*TokenReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Token not implemented")
}
func (UnimplementedPublishersServer) mustEmbedUnimplementedPublishersServer() {}

// UnsafePublishersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublishersServer will
// result in compilation errors.
type UnsafePublishersServer interface {
	mustEmbedUnimplementedPublishersServer()
}

func RegisterPublishersServer(s grpc.ServiceRegistrar, srv PublishersServer) {
	s.RegisterService(&Publishers_ServiceDesc, srv)
}

func _Publishers_Token_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublishersServer).Token(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taoniu.local.account.grpc.mqtt.publishers.Publishers/Token",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublishersServer).Token(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Publishers_ServiceDesc is the grpc.ServiceDesc for Publishers service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Publishers_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "taoniu.local.account.grpc.mqtt.publishers.Publishers",
	HandlerType: (*PublishersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Token",
			Handler:    _Publishers_Token_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account/mqtt/publishers/publishers.proto",
}
