// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: mqtt/publishers/publishers.proto

package publishers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AccessTokenRequest) Reset() {
	*x = AccessTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mqtt_publishers_publishers_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessTokenRequest) ProtoMessage() {}

func (x *AccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mqtt_publishers_publishers_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessTokenRequest.ProtoReflect.Descriptor instead.
func (*AccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_mqtt_publishers_publishers_proto_rawDescGZIP(), []int{0}
}

func (x *AccessTokenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AccessTokenReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken []string `protobuf:"bytes,1,rep,name=accessToken,proto3" json:"accessToken,omitempty"`
}

func (x *AccessTokenReply) Reset() {
	*x = AccessTokenReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mqtt_publishers_publishers_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessTokenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessTokenReply) ProtoMessage() {}

func (x *AccessTokenReply) ProtoReflect() protoreflect.Message {
	mi := &file_mqtt_publishers_publishers_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessTokenReply.ProtoReflect.Descriptor instead.
func (*AccessTokenReply) Descriptor() ([]byte, []int) {
	return file_mqtt_publishers_publishers_proto_rawDescGZIP(), []int{1}
}

func (x *AccessTokenReply) GetAccessToken() []string {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

var File_mqtt_publishers_publishers_proto protoreflect.FileDescriptor

var file_mqtt_publishers_publishers_proto_rawDesc = []byte{
	0x0a, 0x20, 0x6d, 0x71, 0x74, 0x74, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72,
	0x73, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x29, 0x74, 0x61, 0x6f, 0x6e, 0x69, 0x75, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c,
	0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x71,
	0x74, 0x74, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x73, 0x22, 0x24, 0x0a,
	0x12, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x10, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x32, 0x9a, 0x01, 0x0a, 0x0a, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x73, 0x12, 0x8b, 0x01, 0x0a, 0x0b, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x3d, 0x2e, 0x74, 0x61, 0x6f, 0x6e, 0x69,
	0x75, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x71, 0x74, 0x74, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x65, 0x72, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3b, 0x2e, 0x74, 0x61, 0x6f, 0x6e, 0x69, 0x75,
	0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x6d, 0x71, 0x74, 0x74, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x65, 0x72, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x2b, 0x5a, 0x29, 0x74, 0x61, 0x6f, 0x6e, 0x69, 0x75,
	0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x6d, 0x71, 0x74, 0x74, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x65, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mqtt_publishers_publishers_proto_rawDescOnce sync.Once
	file_mqtt_publishers_publishers_proto_rawDescData = file_mqtt_publishers_publishers_proto_rawDesc
)

func file_mqtt_publishers_publishers_proto_rawDescGZIP() []byte {
	file_mqtt_publishers_publishers_proto_rawDescOnce.Do(func() {
		file_mqtt_publishers_publishers_proto_rawDescData = protoimpl.X.CompressGZIP(file_mqtt_publishers_publishers_proto_rawDescData)
	})
	return file_mqtt_publishers_publishers_proto_rawDescData
}

var file_mqtt_publishers_publishers_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mqtt_publishers_publishers_proto_goTypes = []interface{}{
	(*AccessTokenRequest)(nil), // 0: taoniu.local.account.grpc.mqtt.publishers.AccessTokenRequest
	(*AccessTokenReply)(nil),   // 1: taoniu.local.account.grpc.mqtt.publishers.AccessTokenReply
}
var file_mqtt_publishers_publishers_proto_depIdxs = []int32{
	0, // 0: taoniu.local.account.grpc.mqtt.publishers.Publishers.AccessToken:input_type -> taoniu.local.account.grpc.mqtt.publishers.AccessTokenRequest
	1, // 1: taoniu.local.account.grpc.mqtt.publishers.Publishers.AccessToken:output_type -> taoniu.local.account.grpc.mqtt.publishers.AccessTokenReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mqtt_publishers_publishers_proto_init() }
func file_mqtt_publishers_publishers_proto_init() {
	if File_mqtt_publishers_publishers_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mqtt_publishers_publishers_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mqtt_publishers_publishers_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessTokenReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mqtt_publishers_publishers_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mqtt_publishers_publishers_proto_goTypes,
		DependencyIndexes: file_mqtt_publishers_publishers_proto_depIdxs,
		MessageInfos:      file_mqtt_publishers_publishers_proto_msgTypes,
	}.Build()
	File_mqtt_publishers_publishers_proto = out.File
	file_mqtt_publishers_publishers_proto_rawDesc = nil
	file_mqtt_publishers_publishers_proto_goTypes = nil
	file_mqtt_publishers_publishers_proto_depIdxs = nil
}
