// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: aes/aes.proto

package aes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecryptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             string                 `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B             string                 `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	C             string                 `protobuf:"bytes,3,opt,name=c,proto3" json:"c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptRequest) Reset() {
	*x = DecryptRequest{}
	mi := &file_aes_aes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptRequest) ProtoMessage() {}

func (x *DecryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aes_aes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptRequest.ProtoReflect.Descriptor instead.
func (*DecryptRequest) Descriptor() ([]byte, []int) {
	return file_aes_aes_proto_rawDescGZIP(), []int{0}
}

func (x *DecryptRequest) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *DecryptRequest) GetB() string {
	if x != nil {
		return x.B
	}
	return ""
}

func (x *DecryptRequest) GetC() string {
	if x != nil {
		return x.C
	}
	return ""
}

type DecryptReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptReply) Reset() {
	*x = DecryptReply{}
	mi := &file_aes_aes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptReply) ProtoMessage() {}

func (x *DecryptReply) ProtoReflect() protoreflect.Message {
	mi := &file_aes_aes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptReply.ProtoReflect.Descriptor instead.
func (*DecryptReply) Descriptor() ([]byte, []int) {
	return file_aes_aes_proto_rawDescGZIP(), []int{1}
}

func (x *DecryptReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_aes_aes_proto protoreflect.FileDescriptor

const file_aes_aes_proto_rawDesc = "" +
	"\n" +
	"\raes/aes.proto\x12\x17security.local.grpc.aes\":\n" +
	"\x0eDecryptRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\tR\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\tR\x01b\x12\f\n" +
	"\x01c\x18\x03 \x01(\tR\x01c\"&\n" +
	"\fDecryptReply\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2b\n" +
	"\x03Aes\x12[\n" +
	"\aDecrypt\x12'.security.local.grpc.aes.DecryptRequest\x1a%.security.local.grpc.aes.DecryptReply\"\x00B Z\x1etaoniu.local/security/grpc/aesb\x06proto3"

var (
	file_aes_aes_proto_rawDescOnce sync.Once
	file_aes_aes_proto_rawDescData []byte
)

func file_aes_aes_proto_rawDescGZIP() []byte {
	file_aes_aes_proto_rawDescOnce.Do(func() {
		file_aes_aes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aes_aes_proto_rawDesc), len(file_aes_aes_proto_rawDesc)))
	})
	return file_aes_aes_proto_rawDescData
}

var file_aes_aes_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aes_aes_proto_goTypes = []any{
	(*DecryptRequest)(nil), // 0: security.local.grpc.aes.DecryptRequest
	(*DecryptReply)(nil),   // 1: security.local.grpc.aes.DecryptReply
}
var file_aes_aes_proto_depIdxs = []int32{
	0, // 0: security.local.grpc.aes.Aes.Decrypt:input_type -> security.local.grpc.aes.DecryptRequest
	1, // 1: security.local.grpc.aes.Aes.Decrypt:output_type -> security.local.grpc.aes.DecryptReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aes_aes_proto_init() }
func file_aes_aes_proto_init() {
	if File_aes_aes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aes_aes_proto_rawDesc), len(file_aes_aes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aes_aes_proto_goTypes,
		DependencyIndexes: file_aes_aes_proto_depIdxs,
		MessageInfos:      file_aes_aes_proto_msgTypes,
	}.Build()
	File_aes_aes_proto = out.File
	file_aes_aes_proto_goTypes = nil
	file_aes_aes_proto_depIdxs = nil
}
